site_name: "abacus: accounting in code"
repo_url: "https://github.com/epogrebnyak/abacus"
site_url: "https://epogrebnyak.github.io/abacus/"
copyright: "&copy; 2023-2024 Evgeniy Pogrebnyak"
nav:
  - "A minimal, yet valid double entry accounting system": index.md
  - quick_start.md
  - examples.md
  - How `abacus` works:
      - how-it-works/inside.md
  - Accounting basics:
      - accounting/introduction.md
      - accounting/chart_of_accounts.md
  - More about project:
      - about/motivation.md
      - about/quotes.md
      - about/rules.md
      - about/similar.md

theme:
  name: material
  logo: assets/robot.png
  features:
    - navigation.expand

plugins:
  - search
