site_name: "abacus: accounting in code"
repo_url: "https://github.com/epogrebnyak/abacus"
site_url: "https://epogrebnyak.github.io/abacus/"
copyright: "&copy; 2023 Evgeny Pogrebnyak"
nav:
  - "A minimal, yet valid double entry accounting system": index.md
  - "Accounting equations": accounting.md
  - "Chart of accounts": chart_of_accounts.md
  - "Making of": rules.md
  - "Similar projects": similar.md
  - "API Reference": reference.md

theme:
  name: material

plugins:
  - search
#  - mkdocstrings
