site_name: "abacus: accounting in code"
repo_url: "https://github.com/epogrebnyak/abacus"
site_url: "https://epogrebnyak.github.io/abacus/"
copyright: "&copy; 2023-2024 Evgeniy Pogrebnyak"
nav:
  - index.md
  - quick_start.md
  - Accounting basics:
      - accounting/introduction.md
      - accounting/chart_of_accounts.md
  - More about project:
      - about/motivation.md
      - about/quotes.md
      - about/similar.md
  - reference.md

theme:
  name: material
  logo: assets/robot.png
  features:
    #- navigation.expand
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
           options:
              show_bases: true
              show_root_heading: true
              show_source: true              