site_name: "abacus (accounting framework)"
repo_url: "https://github.com/epogrebnyak/abacus"
site_url: "https://epogrebnyak.github.io/abacus/"
copyright: "&copy; 2023 Evgeny Pogrebnyak"
nav:
  - About: index.md
  - API: reference.md
  - "Accounting equations": accounting.md
theme:
  name: material

plugins:
  - search
  - mkdocstrings
