# move to tests
# ChartCommand.new().promote("asset:cash").write("chart.json")
# ChartCommand.new().promote("asset:cash").write("chart.json")
# ChartCommand.read("chart.json").promote("cash").write("chart.json")
# ChartCommand.read("chart.json").promote("expense:ads").write("chart.json")
# ChartCommand.read("chart.json").promote("ads").write("chart.json")
# ChartCommand.read("chart.json").promote("capital:equity").write("chart.json")
# ChartCommand.read("chart.json").promote("contra:equity:withdrawals").write("chart.json")
# ChartCommand.read("chart.json").promote("contra:equity:treasury_stock").write("chart.json")
# ChartCommand.read("chart.json").chart.json(indent=2)
